apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixcat
  labels:
    app: netflixcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixcat
  template:
    metadata:
        labels:
          app: netflixcat
    spec:
      containers:
      - name: netflixcat
        image: jag129/net_cat:0.0.1

---
# 2. net_cat k8s yaml for service
apiVersion: v1
kind: Service
metadata:
  name: netflixcat
  labels:
    app: netflixcat
spec:
  selector:
    app: netflixcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
