apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
  labels:
    app: netflix-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
        labels:
          app: netflix-frontend
    spec:
      containers:
      - name: server
        image: jag129/net_front:0.0.1
        env:
        - name: MOVIE_CATALOG_SERVICE
          value: "http://netflixcat:8080"
        - name: AWS_SQS_QUEUE_URL
          value: "https://sqs.eu-north-1.amazonaws.com/352708296901/yishai-netflix-events"
        - name: AWS_REGION
          value: "EU-NORTH-1"

---
apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend-service
spec:
  selector:
    app: netflix-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

